### ISSUE TITLE
[Fix] API 수정 및 API 추가

### ISSUE THREAD

**Issue by yeomj051** [Techeer-H/backend#16]
**기능에 대한 설명**
로그인 및 회원가입 API 수정, 메모 수정 API 추가

**TODO List**
- [ ] 로그인 Response 수정
- [ ] 회원가입 API에 Memo 기능 추가
- [ ] Memo 수정 API 구현
- [ ] Django 화면 깨짐 해결
