### ISSUE TITLE
[Feature] 학생 조회/등록, 성적 조회/등록 API개발

### ISSUE THREAD

**Issue by yeomj051** [Techeer-H/backend#4]
**기능에 대한 설명**
학생 조회 : student_id 혹은 student_name으로 학생 리스트 조회
학생 등록 : 학생의 정보를 등록
학생 성적 조회 : 학생 아이디(+과목 아이디)로 학생의 성정을 조회
학생 성적 등록 : 컨설턴트 혹은 강사가 학생의 성적을 등록

**TODO List**
- [ ] 학생조회 API 개발
- [ ] 학생등록 API 개발
- [ ]  학생 성적 조회 API개발
- [ ]  학생 성적 등록 API개발
- [ ] postman으로 테스트
